// Auto-generated by scripts/generate-famous-verses.mjs — DO NOT EDIT BY HAND.
// Source verses: 13:28, 94:5, 2:152, 65:3, 39:53, 2:286.
// Translation sources per locale: see the SOURCES map in the generator.

import type { Locale } from "@/i18n/routing";

export interface FamousVerseLocalized {
  translation: string;
  /** Short surah name in this locale's script (e.g. "Корова", "The Cow"). */
  surah: string;
  /** Translator credit shown under the verse, ALL CAPS where the script supports it. */
  cite: string;
}

export interface FamousVerse {
  surah: number;
  ayah: number;
  arabic: string;
  /** Pre-built audio URL (Quran.com CDN, Abdul-Basit Mujawwad). */
  audioUrl: string;
  byLocale: Record<Locale, FamousVerseLocalized>;
}

export const FAMOUS_VERSES: FamousVerse[] = [
  {
    surah: 13,
    ayah: 28,
    arabic: "ٱلَّذِينَ ءَامَنُواْ وَتَطۡمَئِنُّ قُلُوبُهُم بِذِكۡرِ ٱللَّهِۗ أَلَا بِذِكۡرِ ٱللَّهِ تَطۡمَئِنُّ ٱلۡقُلُوبُ",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/013028.mp3",
    byLocale: {
      ru: {
        translation: "Они уверовали, и их сердца утешаются поминанием Аллаха. Разве не поминанием Аллаха утешаются сердца",
        surah: "Гром",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "Those who have believed and whose hearts are assured by the remembrance of Allah. Unquestionably, by the remembrance of Allah hearts are assured.\"",
        surah: "The Thunder",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "ٱلَّذِينَ ءَامَنُواْ وَتَطۡمَئِنُّ قُلُوبُهُم بِذِكۡرِ ٱللَّهِۗ أَلَا بِذِكۡرِ ٱللَّهِ تَطۡمَئِنُّ ٱلۡقُلُوبُ",
        surah: "الرعد",
        cite: "النص العثماني",
      },
      fa: {
        translation: "آنها کسانی هستند که ایمان آورده‌اند، و دلهایشان به یاد خدا مطمئن (و آرام) است؛ آگاه باشید، تنها با یاد خدا دلها آرامش می‌یابد",
        surah: "رعد",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "Онҳое, ки имон овардаанд ва дилҳояшон ба ёди Худо оромиш меёбад, огоҳ бошед, ки дилҳо ба ёди Худо оромиш меёбад!",
        surah: "Раъд",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "Улар иймон келтирган ва қалблари Аллоҳни зикр қилиш — эслаш билан ором оладиган зотлардир. Огоҳ бўлингизким, Аллоҳни зикр қилиш билан қалблар ором олур",
        surah: "Raʼd",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "Сондай иман келтіргендер; Алланы еске алу арқылы көңілдері жай тапқандар. Естеріңде болсын; Алланы еске алумен жүректер орнығады.",
        surah: "Раъд",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Аллах туура жолго баштаган адамдар – алар Аллахка ыйман келтирип, Аллахты аруулап, мактап, Куранды окуп жана угуп зикр кылганда жүрөктөрү тынчтанган адамдар. Көңүл бургула! Жалгыз Аллахты эстөө менен жүрөктөр тынчтанат. Аллах жүрөктү ушул үчүн жараткан.",
        surah: "Рад",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "جو لوگ ایمان ﻻئے ان کے دل اللہ کے ذکر سے اطمینان حاصل کرتے ہیں۔ یاد رکھو اللہ کے ذکر سے ہی دلوں کو تسلی حاصل ہوتی ہے",
        surah: "الرعد",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "(Iaitu) orang-orang yang beriman dan tenang tenteram hati mereka dengan zikrullah\". Ketahuilah dengan \"zikrullah\" itu, tenang tenteramlah hati manusia",
        surah: "Ar-Ra’d",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "और जिसने उसकी तरफ रुज़ू की उसे अपनी तरफ पहुँचने की राह दिखाता है (ये) वह लोग हैं जिन्होंने ईमान कुबूल किया और उनके दिलों को ख़ुदा की चाह से तसल्ली हुआ करती है",
        surah: "अर-रअद",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "(yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram",
        surah: "Ar-Ra’d",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
  {
    surah: 94,
    ayah: 5,
    arabic: "فَإِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/094005.mp3",
    byLocale: {
      ru: {
        translation: "Воистину, за каждой тягостью наступает облегчение",
        surah: "Раскрытие",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "For indeed, with hardship [will be] ease.",
        surah: "The Relief",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "فَإِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا",
        surah: "الشرح",
        cite: "النص العثماني",
      },
      fa: {
        translation: "به یقین با (هر) سختی آسانی است",
        surah: "شرح",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "Пас аз паи душворӣ осонист!",
        surah: "Шарҳ",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "Бас, албатта ҳар бир оғирлик-машаққат билан бирга бир енгиллик ҳам бордир",
        surah: "Sharh",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "Негізінде ауырлықпен бірге бір жеңілдік бар.",
        surah: "Шарх",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Албетте, кыйынчылык жана кысылуу менен бирге жеңилдик кененчилик жана кутулуу да бар.",
        surah: "Шарх",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "پس یقیناً مشکل کے ساتھ آسانی ہے",
        surah: "الشرح",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "Oleh itu, maka (tetapkanlah kepercayaanmu) bahawa sesungguhnya tiap-tiap kesukaran disertai kemudahan",
        surah: "Asy-Syarh",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "तो (हाँ) पस बेशक दुशवारी के साथ ही आसानी है",
        surah: "अश-शरह",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "Maka sesungguhnya bersama kesulitan ada kemudahan",
        surah: "Asy-Syarh",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
  {
    surah: 2,
    ayah: 152,
    arabic: "فَٱذۡكُرُونِيٓ أَذۡكُرۡكُمۡ وَٱشۡكُرُواْ لِي وَلَا تَكۡفُرُونِ",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/002152.mp3",
    byLocale: {
      ru: {
        translation: "Поминайте Меня, и Я буду помнить о вас. Благодарите Меня и не будьте неблагодарны Мне",
        surah: "Корова",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "So remember Me; I will remember you. And be grateful to Me and do not deny Me.",
        surah: "The Cow",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "فَٱذۡكُرُونِيٓ أَذۡكُرۡكُمۡ وَٱشۡكُرُواْ لِي وَلَا تَكۡفُرُونِ",
        surah: "البقرة",
        cite: "النص العثماني",
      },
      fa: {
        translation: "پس به یاد من باشید، تا به یاد شما باشم! و شکر مرا گویید و (در برابر نعمتهایم) کفران نکنید",
        surah: "بقره",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "Пас моро ёд кунед, то шуморо ёд кунам. Маро сипос гӯед ва носипосии ман накунед.",
        surah: "Бақара",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "Бас, Мени эслангиз, Мен ҳам сизларни эслайман ва Менга шукр қилингиз ва Менга куфр келтирмангиз",
        surah: "Baqara",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "Енді, Мені еске алыңдар, Мен де сендерді еске аламын және Маған шүкірлік кылыңдар да қарсы болмаңдар.",
        surah: "Бақара",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Мени жүрөгүңөр жана дене мүчөңөр эстегиле, ошондо Мен дагы силерди мактоо жана сактоо менен эстеймин. Анткени сыйлык иш-аракеттин түрүнө жараша болот. Силерге берген жакшылыктарым үчүн Мага шүгүр кылгыла жана аларды четке кагып, силерге арам болгон жолдо колдонуп Мага каапырлык кылбагыла.",
        surah: "Бакара",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "اس لئے تم میرا ذکر کرو، میں بھی تمہیں یاد کروں گا، میری شکر گزاری کرو اور ناشکری سے بچو",
        surah: "البقرة",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "Oleh itu ingatlah kamu kepadaKu (dengan mematuhi hukum dan undang-undangKu), supaya Aku membalas kamu dengan kebaikan; dan bersyukurlah kamu kepadaKu dan janganlah kamu kufur (akan nikmatKu)",
        surah: "Al-Baqarah",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "पस तुम हमारी याद रखो तो मै भी तुम्हारा ज़िक्र (खैर) किया करुगाँ और मेरा शुक्रिया अदा करते रहो और नाशुक्री न करो",
        surah: "अल-बक़रह",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "(Maka ingatlah kepada-Ku, Aku pun akan ingat kepadamu.50) Bersyukurlah kepada-Ku, dan janganlah kamu ingkar kepada-Ku",
        surah: "Al-Baqarah",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
  {
    surah: 65,
    ayah: 3,
    arabic: "وَيَرۡزُقۡهُ مِنۡ حَيۡثُ لَا يَحۡتَسِبُۚ وَمَن يَتَوَكَّلۡ عَلَى ٱللَّهِ فَهُوَ حَسۡبُهُۥٓۚ إِنَّ ٱللَّهَ بَٰلِغُ أَمۡرِهِۦۚ قَدۡ جَعَلَ ٱللَّهُ لِكُلِّ شَيۡءࣲ قَدۡرࣰ ا",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/065003.mp3",
    byLocale: {
      ru: {
        translation: "и наделяет его уделом оттуда, откуда он даже не предполагает. Тому, кто уповает на Аллаха, достаточно Его. Аллах доводит до конца Свое дело. Аллах установил меру для каждой вещи",
        surah: "Развод",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "And will provide for him from where he does not expect. And whoever relies upon Allah - then He is sufficient for him. Indeed, Allah will accomplish His purpose. Allah has already set for everything a [decreed] extent.",
        surah: "Divorce",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "وَيَرۡزُقۡهُ مِنۡ حَيۡثُ لَا يَحۡتَسِبُۚ وَمَن يَتَوَكَّلۡ عَلَى ٱللَّهِ فَهُوَ حَسۡبُهُۥٓۚ إِنَّ ٱللَّهَ بَٰلِغُ أَمۡرِهِۦۚ قَدۡ جَعَلَ ٱللَّهُ لِكُلِّ شَيۡءࣲ قَدۡرࣰ ا",
        surah: "الطلاق",
        cite: "النص العثماني",
      },
      fa: {
        translation: "و او را از جایی که گمان ندارد روزی می‌دهد؛ و هر کس بر خدا توکّل کند، کفایت امرش را می‌کند؛ خداوند فرمان خود را به انجام می‌رساند؛ و خدا برای هر چیزی اندازه‌ای قرار داده است",
        surah: "طلاق",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "ва аз ҷое, ки гумонашро надорад, рӯзиаш медиҳад. Ва ҳар кӣ бар Худо таваккал кунад, Худо ӯро кофист. Худо кори худро ба иҷро мерасонад ва ҳар чизро андозае қарор додааст.",
        surah: "Талоқ",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "Ва уни ўзи ўйламаган томондан ризқлантирур. Ким Аллоҳга таваккул қилса, бас, (Аллоҳнинг) Ўзи унга етарлидир. Албатта Аллоҳ Ўзи (хоҳлаган) ишига етгувчидир. (Унинг хоҳишига қарши тургувчи кимса йўқдир). Дарҳақиқат, Аллоҳ барча нарса учун миқдор-ўлчов қилиб қўйгандир (яъни, ҳаётда рўй берадиган ҳар бир яхши-ёмон воқеа-ҳодиса ёлғиз Аллоҳ хоҳлаган — белгилаган вақт ва ўлчовда рўй беради)",
        surah: "Taloq",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "Оған, Алла, ойламаған жерден ризық береді. Ал кім Аллаға тәуекел қылса, сонда Ол, оған жетіп асады. Сөзсіз Алла өз бұйрығын атқарады. Расында Алла, әр нәрсеге бір өлшеу қойған.",
        surah: "Талаq",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Жана ага оюна келбеген тараптан ырыскы берет. Ким өз иштеринде Аллахка таянса, Ал ага жетиштүү. Чындыгында Аллах Өз буйругун ишке ашыруучу. Аны эч нерсе алсырата албайт жана Ал бир дагы нерсени өткөрүп жибербейт. Аллах ар бир нерсенин бүтө турган өлчөмүн белгилеп койгон. Кыйынчылыктын да өлчөмү бар, бакубатчылыктын да өлчөмү бар. Инсанда алардын бирөөсү эле дайым боло бербейт.",
        surah: "Талак",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "اور اسے ایسی جگہ سے روزی دیتا ہے جس کا اسے گمان بھی نہ ہو اور جو شخص اللہ پر توکل کرے گا اللہ اسے کافی ہوگا۔ اللہ تعالیٰ اپنا کام پورا کرکے ہی رہے گا۔ اللہ تعالیٰ نے ہر چیز کا ایک اندازه مقرر کر رکھا ہے",
        surah: "الطلاق",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "Serta memberinya rezeki dari jalan yang tidak terlintas di hatinya. Dan (Ingatlah), sesiapa berserah diri bulat-bulat kepada Allah, maka Allah cukuplah baginya (untuk menolong dan menyelamatkannya). Sesungguhnya Allah tetap melakukan segala perkara yang dikehendakiNya. Allah telahpun menentukan kadar dan masa bagi berlakunya tiap-tiap sesuatu",
        surah: "At-Talaq",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "और उसको ऐसी जगह से रिज़क़ देगा जहाँ से वहम भी न हो और जिसने ख़ुदा पर भरोसा किया तो वह उसके लिए काफी है बेशक ख़ुदा अपने काम को पूरा करके रहता है ख़ुदा ने हर चीज़ का एक अन्दाज़ा मुक़र्रर कर रखा है",
        surah: "अत-तलाक़",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "Dan Dia memberinya rezeki dari arah yang tidak disangka-sangkanya. Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya. Sesungguhnya Allah melaksanakan urusan-Nya. Sungguh, Allah telah mengadakan ketentuan bagi setiap sesuatu",
        surah: "At-Talaq",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
  {
    surah: 39,
    ayah: 53,
    arabic: "۞قُلۡ يَٰعِبَادِيَ ٱلَّذِينَ أَسۡرَفُواْ عَلَىٰٓ أَنفُسِهِمۡ لَا تَقۡنَطُواْ مِن رَّحۡمَةِ ٱللَّهِۚ إِنَّ ٱللَّهَ يَغۡفِرُ ٱلذُّنُوبَ جَمِيعًاۚ إِنَّهُۥ هُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/039053.mp3",
    byLocale: {
      ru: {
        translation: "Скажи Моим рабам, которые излишествовали во вред самим себе: «Не отчаивайтесь в милости Аллаха. Воистину, Аллах прощает грехи полностью, ибо Он - Прощающий, Милосердный»",
        surah: "Толпы",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "Say, \"O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.\"",
        surah: "The Throngs",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "۞قُلۡ يَٰعِبَادِيَ ٱلَّذِينَ أَسۡرَفُواْ عَلَىٰٓ أَنفُسِهِمۡ لَا تَقۡنَطُواْ مِن رَّحۡمَةِ ٱللَّهِۚ إِنَّ ٱللَّهَ يَغۡفِرُ ٱلذُّنُوبَ جَمِيعًاۚ إِنَّهُۥ هُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ",
        surah: "الزمر",
        cite: "النص العثماني",
      },
      fa: {
        translation: "بگو: «ای بندگان من که بر خود اسراف و ستم کرده‌اید! از رحمت خداوند نومید نشوید که خدا همه گناهان را می‌آمرزد، زیرا او بسیار آمرزنده و مهربان است",
        surah: "زمر",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "Бигӯ: «Эй бандагони Ман, ки бар зиёни худ исроф кардаед, аз раҳмати Худо ноумед нашавед. Зеро Худо ҳамаи гуноҳонро мебахшояд. Ӯст бахшояндаву меҳрубон!",
        surah: "Зумар",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "(Эй Муҳаммад алайҳис-салоту вас-салом), Менинг ўз жонларига жиноят қилган (турли гуноҳ-маъсиятлар қилиш билан) бандаларимга айтинг: «Аллоҳнинг раҳмат-марҳаматидан ноумид бўлмангиз! Албатта Аллоҳ (Ўзи хоҳлаган бандаларининг) барча гуноҳларини мағфират қилур. Албатта Унинг Ўзигина мағфиратли, меҳрибондир",
        surah: "Zumar",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "(Мұхаммед Ғ.С.): \"Әй өздеріне зиян қылған құлдарым! Алланың рахметінен күдер үзбеңдер. Алла біртұтас күнәларды жарылқайды. Өйткені Ол тым жарылқаушы, төтенше мейірімді\" де.",
        surah: "Зумар",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Оо, пайгамбар! Аллахка ширк кылып жана күнөөлөрдү кылып чектен чыккан пенделериме айт: «Аллахтын ырайымынан жана күнөөлөрүңөрдү кечирүүсүнөн үмүт үзбөгүлө! Чындыгында Аллах тообо кылгандардын бардык күнөөлөрүн кечирет. Чындыгында Ал тообо кылуучулардын күнөөлөрүн Кечирүүчү, аларга Ырайымдуу».",
        surah: "Зумар",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "(میری جانب سے) کہہ دو کہ اے میرے بندو! جنہوں نے اپنی جانوں پر زیادتی کی ہے تم اللہ کی رحمت سے ناامید نہ ہو جاؤ، بالیقین اللہ تعالیٰ سارے گناہوں کو بخش دیتا ہے، واقعی وه بڑی بخشش بڑی رحمت واﻻ ہے",
        surah: "الزمر",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "Katakanlah (wahai Muhammad): \"Wahai hamba-hambaKu yang telah melampaui batas terhadap diri mereka sendiri (dengan perbuatan-perbuatan maksiat), janganlah kamu berputus asa dari rahmat Allah, kerana sesungguhnya Allah mengampunkan segala dosa; sesungguhnya Dia lah jua Yang Maha Pengampun, lagi Maha Mengasihani",
        surah: "Az-Zumar",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "(ऐ रसूल) तुम कह दो कि ऐ मेरे (ईमानदार) बन्दों जिन्होने (गुनाह करके) अपनी जानों पर ज्यादतियाँ की हैं तुम लोग ख़ुदा की रहमत से नाउम्मीद न होना बेशक ख़ुदा (तुम्हारे) कुल गुनाहों को बख्श देगा वह बेशक बड़ा बख्शने वाला मेहरबान है",
        surah: "अज़-ज़ुमर",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "(Katakanlah, \"Wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri! Janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa765) semuanya. Sungguh, Dialah Yang Maha Pengampun, Maha Penyayang",
        surah: "Az-Zumar",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
  {
    surah: 2,
    ayah: 286,
    arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفۡسًا إِلَّا وُسۡعَهَاۚ لَهَا مَا كَسَبَتۡ وَعَلَيۡهَا مَا ٱكۡتَسَبَتۡۗ رَبَّنَا لَا تُؤَاخِذۡنَآ إِن نَّسِينَآ أَوۡ أَخۡطَأۡنَاۚ رَبَّنَا وَلَا تَحۡمِلۡ عَلَيۡنَآ إِصۡرࣰ ا كَمَا حَمَلۡتَهُۥ عَلَى ٱلَّذِينَ مِن قَبۡلِنَاۚ رَبَّنَا وَلَا تُحَمِّلۡنَا مَا لَا طَاقَةَ لَنَا بِهِۦۖ وَٱعۡفُ عَنَّا وَٱغۡفِرۡ لَنَا وَٱرۡحَمۡنَآۚ أَنتَ مَوۡلَىٰنَا فَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ",
    audioUrl: "https://verses.quran.com/AbdulBaset/Mujawwad/mp3/002286.mp3",
    byLocale: {
      ru: {
        translation: "Аллах не возлагает на человека сверх его возможностей. Ему достанется то, что он приобрел, и против него будет то, что он приобрел. Господь наш! Не наказывай нас, если мы позабыли или ошиблись. Господь наш! Не возлагай на нас бремя, которое Ты возложил на наших предшественников. Господь наш! Не обременяй нас тем, что нам не под силу. Будь снисходителен к нам! Прости нас и помилуй! Ты - наш Покровитель. Помоги же нам одержать верх над неверующими людьми",
        surah: "Корова",
        cite: "ПЕРЕВОД Э. КУЛИЕВА",
      },
      en: {
        translation: "Allah does not charge a soul except [with that within] its capacity. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned. \"Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.\"",
        surah: "The Cow",
        cite: "SAHIH INTERNATIONAL",
      },
      ar: {
        translation: "لَا يُكَلِّفُ ٱللَّهُ نَفۡسًا إِلَّا وُسۡعَهَاۚ لَهَا مَا كَسَبَتۡ وَعَلَيۡهَا مَا ٱكۡتَسَبَتۡۗ رَبَّنَا لَا تُؤَاخِذۡنَآ إِن نَّسِينَآ أَوۡ أَخۡطَأۡنَاۚ رَبَّنَا وَلَا تَحۡمِلۡ عَلَيۡنَآ إِصۡرࣰ ا كَمَا حَمَلۡتَهُۥ عَلَى ٱلَّذِينَ مِن قَبۡلِنَاۚ رَبَّنَا وَلَا تُحَمِّلۡنَا مَا لَا طَاقَةَ لَنَا بِهِۦۖ وَٱعۡفُ عَنَّا وَٱغۡفِرۡ لَنَا وَٱرۡحَمۡنَآۚ أَنتَ مَوۡلَىٰنَا فَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ",
        surah: "البقرة",
        cite: "النص العثماني",
      },
      fa: {
        translation: "خداوند هیچ کس را، جز به اندازه تواناییش، تکلیف نمی‌کند. (انسان،) هر کار (نیکی) را انجام دهد، برای خود انجام داده؛ و هر کار (بدی) کند، به زیان خود کرده است. (مؤمنان می‌گویند:) پروردگارا! اگر ما فراموش یا خطا کردیم، ما را مؤاخذه مکن! پروردگارا! تکلیف سنگینی بر ما قرار مده، آن چنان که (به خاطر گناه و طغیان،) بر کسانی که پیش از ما بودند، قرار دادی! پروردگارا! آنچه طاقت تحمل آن را نداریم، بر ما مقرّر مدار! و آثار گناه را از ما بشوی! ما را ببخش و در رحمت خود قرار ده! تو مولا و سرپرست مایی، پس ما را بر جمعیّت کافران، پیروز گردان",
        surah: "بقره",
        cite: "ترجمه مکارم شیرازی",
      },
      tg: {
        translation: "Худо ҳеҷ касро ҷуз ба андозаи тоқаташ амр намекунад. Некиҳои ҳар кас аз они худи уст ва бадиҳояш аз они худи ӯст. «Эй Парвардигори мо, агар фаромӯш кардаем ё хатое кар даем, моро бозхост макун! Эй Парвардигори мо, он гуна ки бар умматҳои пеш аз мо таклифи вазнин ниҳодӣ, таклифи вазнин бар мо манеҳ ва он чиро, ки тоқати он надорем, бар мо таклиф макун! Гуноҳи мо бубахш ва моро биёмурз ва бар мо раҳмат овар! Ту хоҷаи мо хастӣ. Пас моро бар гурӯҳи кофирон ғолиб гардон!»",
        surah: "Бақара",
        cite: "ТАРҶУМАИ ОЯТӢ",
      },
      uz: {
        translation: "Аллоҳ ҳеч бир жонни тоқатидан ташқари нарсага таклиф қилмайди. (Ҳар кимнинг) қилган (яхши) амали ўзи учундир ва (ёмон) амали ҳам ўзининг бўйнигадир. Парвардигоро, агар унутган ёки хато қилган бўлсак, бизни азобингга гирифтор айлама! Парвардигоро, бизларнинг зиммамизга биздан илгари ўтганларнинг буйинларига қўйган юкингни юклама! Парвардигоро, бизларни тоқатимиз етмайдиган нарсага зўрлама! Бизларни афв эт, (гуноҳларимизни) мағфират қил, (ҳолимизга) раҳм айла! Ўзинг Хожамизсан! Бас, бу кофир қавм устига Ўзинг бизни ғолиб қил",
        surah: "Baqara",
        cite: "ALOUDDIN MANSUR TARJIMASI",
      },
      kk: {
        translation: "Алла (Т.) кісіге шамасы келетін міндетті ғана жүктейді; істеген жақсылығы өз пайдасына да, жамандығы зиянына. «Раббымыз! Егер ұмытсақ не жаңылсақ бізді қолға алма. Раббымыз! Бізге бізден бұрынғыларға жүктегеніңдей ауыр жүк жүктеме. Раббым! Бізге шамамыз келмейтінді артпа! Бізді кешір, бізді жарылқа, бізге мәрхамет ет. Сен иемізсің! Бізге кәпір қауымға қарсы жәрдем бер!»",
        surah: "Бақара",
        cite: "ХАЛИФА АЛТАЙ АУДАРМАСЫ",
      },
      ky: {
        translation: "Аллах эч бир жанга анын мүмкүнчүлүгүнөн ашыкча нерсени жүктөбөйт. Анткени Аллахтын дини жеңилдикке негизделген, анда эч кандай кыйынчылык жок. Ким жакшылык кылса, анын сыйлыгын алат, андан эч нерсе кемитилбейт. Ким жамандык кылса, анын жазасын тартат, аны башка бирөө көтөрбөйт. Пайгамбар жана ыймандуулар айтышты: «Оо, Раббибиз! Кайсы бир иште же сөздө атайлабастан ката кетирсек же унутуп калсак бизди азаптаба. Оо, Раббибиз! Сен бизден мурун зулумдуктары себептүү жазалаган жөөттөргө милдет кылгандай бизге оорчулукту жараткан жана аткара албаган иштерди милдет кылба, бизге кыйынчылыкты жараткан жана күчүбүз жетпеген буйруктарды жана тыюуларды жүктөбө, күнөөлөрүбүздү кеч, бизди кечир жана бизге айкөлдүгүң менен ырайым кыл. Сен биздин Комкорчубузсуң жана Колдоочубузсуң, каапырлар коомуна каршы бизге жардам бер».",
        surah: "Бакара",
        cite: "МУХТАСАР ТАФСИРИ",
      },
      ur: {
        translation: "اللہ تعالیٰ کسی جان کو اس کی طاقت سے زیاده تکلیف نہیں دیتا، جو نیکی وه کرے وه اس کے لئے اور جو برائی وه کرے وه اس پر ہے، اے ہمارے رب! اگر ہم بھول گئے ہوں یا خطا کی ہو تو ہمیں نہ پکڑنا، اے ہمارے رب! ہم پر وه بوجھ نہ ڈال جو ہم سے پہلے لوگوں پر ڈاﻻ تھا، اے ہمارے رب! ہم پر وه بوجھ نہ ڈال جس کی ہمیں طاقت نہ ہو اور ہم سے درگزر فرما! اور ہمیں بخش دے اور ہم پر رحم کر! تو ہی ہمارا مالک ہے، ہمیں کافروں کی قوم پر غلبہ عطا فرما",
        surah: "البقرة",
        cite: "ترجمہ جوناگڑھی",
      },
      ms: {
        translation: "Allah tidak memberati seseorang melainkan apa yang terdaya olehnya. Ia mendapat pahala kebaikan yang diusahakannya, dan ia juga menanggung dosa kejahatan yang diusahakannya. (Mereka berdoa dengan berkata): \"Wahai Tuhan kami! Janganlah Engkau mengirakan kami salah jika kami lupa atau kami tersalah. Wahai Tuhan kami ! Janganlah Engkau bebankan kepada kami bebanan yang berat sebagaimana yang telah Engkau bebankan kepada orang-orang yang terdahulu daripada kami. Wahai Tuhan kami! Janganlah Engkau pikulkan kepada kami apa yang kami tidak terdaya memikulnya. Dan maafkanlah kesalahan kami, serta ampunkanlah dosa kami, dan berilah rahmat kepada kami. Engkaulah Penolong kami; oleh itu, tolonglah kami untuk mencapai kemenangan terhadap kaum-kaum yang kafir",
        surah: "Al-Baqarah",
        cite: "TERJEMAHAN BASMEIH",
      },
      hi: {
        translation: "और मान लिया परवरदिगार हमें तेरी ही मग़फ़िरत की (ख्वाहिश है) और तेरी ही तरफ़ लौट कर जाना है ख़ुदा किसी को उसकी ताक़त से ज्यादा तकलीफ़ नहीं देता उसने अच्छा काम किया तो अपने नफ़े के लिए और बुरा काम किया तो (उसका वबाल) उसी पर पडेग़ा ऐ हमारे परवरदिगार अगर हम भूल जाऐं या ग़लती करें तो हमारी गिरफ्त न कर ऐ हमारे परवरदिगार हम पर वैसा बोझ न डाल जैसा हमसे अगले लोगों पर बोझा डाला था, और ऐ हमारे परवरदिगार इतना बोझ जिसके उठाने की हमें ताक़त न हो हमसे न उठवा और हमारे कुसूरों से दरगुज़र कर और हमारे गुनाहों को बख्श दे और हम पर रहम फ़रमा तू ही हमारा मालिक है तू ही काफ़िरों के मुक़ाबले में हमारी मदद कर",
        surah: "अल-बक़रह",
        cite: "अनुवाद सुहेल फ़ारूक़",
      },
      id: {
        translation: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. Dia mendapat (pahala) dari kebajikan yang dikerjakannya dan dia mendapat (siksa) dari (kejahatan) yang diperbuatnya. (Mereka berdoa), \"Ya Tuhan kami, janganlah Engkau hukum kami jika kami lupa atau kami melakukan kesalahan. Ya Tuhan kami, janganlah Engkau bebani kami dengan beban yang berat sebagaimana Engkau bebankan kepada orang-orang sebelum kami. Ya Tuhan kami, janganlah Engkau pikulkan kepada kami apa yang tidak sanggup kami memikulnya. Maafkanlah kami, ampunilah kami, dan rahmatilah kami. Engkaulah pelindung kami, maka tolonglah kami menghadapi orang-orang kafir",
        surah: "Al-Baqarah",
        cite: "TERJEMAHAN KEMENAG",
      },
    },
  },
];
